# Generated by Django 6.0.6 on 2026-07-30 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_managers_remove_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('SENIOR', 'Senior Developer'), ('JUNIOR', 'Junior Developer')], default='JUNIOR', max_length=10),
        ),
    ]
