# Generated by Django 6.0.6 on 2026-07-28 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_due_date_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('HIGH', 'Very Important'), ('MEDIUM', 'Important'), ('LOW', 'Less Important')], default='MEDIUM', max_length=20),
        ),
    ]
